# Generated by Django 6.0.5 on 2026-05-06 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Job title, e.g. 'Senior Python Developer'", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Full job description (optional)')),
                ('required_skills', models.TextField(help_text="Comma-separated skills, e.g. 'Python, Django, REST API'")),
                ('is_active', models.BooleanField(default=True, help_text="Inactive jobs don't appear in listings but data is preserved")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', '-created_at'], name='jobs_job_is_acti_5b4a60_idx')],
            },
        ),
    ]
