# Generated by Django 6.0.5 on 2026-05-06 17:12

import candidates.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(help_text='Used as unique identifier for the candidate', max_length=254, unique=True)),
                ('skills', models.TextField(help_text="Comma-separated skills, e.g. 'Python, Django, REST API'")),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, help_text='Optional cover letter from candidate')),
                ('resume', models.FileField(blank=True, help_text='Resume file (PDF, DOC, DOCX)', null=True, upload_to=candidates.models.resume_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Under Review'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='candidates.candidate')),
            ],
            options={
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['job', 'status'], name='candidates__job_id_72b450_idx'), models.Index(fields=['candidate', '-applied_at'], name='candidates__candida_c52037_idx')],
                'unique_together': {('candidate', 'job')},
            },
        ),
    ]
